#!/bin/sh

if [ -z "$username" -o -z "$password" -o -z "$dest" ]; then
  echo "usage: env username=u password=p dest=d updater" >&2
  exit 64
fi

curl=/usr/local/bin/curl
token=`$curl -s -X POST https://api.twitter.com/oauth2/token -u "$username:$password" -H 'Content-Type: application/x-www-form-urlencoded;charset=UTF-8' -d 'grant_type=client_credentials' | sed 's|.*access_token":"\(.*\)",".*|\1|'`
$curl -s "https://api.twitter.com/1.1/search/tweets.json?q=%23codesthlm&count=100" -H "Authorization: Bearer $token" -A "codesthlm" > $dest
